CREATE CONSTRAINT company_uei IF NOT EXISTS FOR (c:Company) REQUIRE c.uei IS UNIQUE;
CREATE CONSTRAINT contract_award_id IF NOT EXISTS FOR (c:Contract) REQUIRE c.award_id IS UNIQUE;
CREATE CONSTRAINT agency_name IF NOT EXISTS FOR (a:Agency) REQUIRE a.name IS UNIQUE;
CREATE CONSTRAINT capability_name IF NOT EXISTS FOR (cap:Capability) REQUIRE cap.name IS UNIQUE;
CREATE CONSTRAINT naics_code IF NOT EXISTS FOR (n:NAICSCode) REQUIRE n.code IS UNIQUE;
